### ISSUE TITLE
Should we continue to reconcile in spite of failures?

### ISSUE THREAD

**Issue by jcantrill** [openshift/elasticsearch-operator#31]
Posing the question if in spite of some failed reconciliations if we should continue to with others[1].  Elasticsearch will never deploy even though if these [1] bits are not available on the cluster, the ES cluster could still function.  IMO, we should consider specifying some error condition in the status but this should not block the ES cluster from  starting.  It is still functional but just doesn't have the appropriate objects in place to be scraped.  Maybe a warning message is more appropriate here.

[1] https://github.com/openshift/elasticsearch-operator/blob/master/pkg/stub/handler.go#L57-L65

**Comment by ewolinetz** [comment]
I think, in general, if it is not completely required for the operator to provide its functionality we should not fail out in our handling and continue processing as you suggest. But I would also think that if its not critical to running, should there be a way to enable that feature instead of having it on by default?
